User/User/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user.urls")),
]

User/user/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

app_name = "user"
urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("profile/", views.User_Update, name="profile_update"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="user/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="user/logout.html"),
        name="logout",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="user/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="user/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="user/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.conf import settings


class User(AbstractUser):
    username = models.CharField(max_length=50, blank=True, null=True, unique=True)
    email = models.EmailField(_("email address"), unique=True)
    native_name = models.CharField(max_length=5)
    phone_no = models.CharField(max_length=11)
    address = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="Profile_images", blank=True, null=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name", "phone_no"]

    def __str__(self):
        return "{}".format(self.email)

User/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "address",
            "phone_no",
            "image",
            "password1",
            "password2",
        ]


class UpdateUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "address",
            "phone_no",
            "image",
        ]

User/user/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, UpdateUserForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        form = CreateUserForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(
                request, f"Account has been created for {username}. continue to login"
            )
            return redirect("user:login")
    else:
        form = CreateUserForm()
    context = {"form": form}
    return render(request, "user/register.html", context)


def User_Update(request):
    if request.method == "POST":
        form = UpdateUserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid:
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(
                request, f"Account has been updated for {username}. continue to login"
            )
            return redirect("user:index")
    else:
        form = UpdateUserForm(instance=request.user)
    context = {"form": form}
    return render(request, "user/update.html", context)


@login_required
def index(request):
    return render(request, "user/index.html")

User/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    <link rel="stylesheet" href="{% static '/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include "partials/nav.html" %}
    {% block content %}{% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
            <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</body>
</html>

User/templates/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {% if user.is_authenticated %}
        <div class="container">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url "user:index" %}">{{ user.username }} Profile <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url "user:logout" %}">Logout</a>
                    </li>
                </ul>
    {% else %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url "user:register" %}">Register <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url "user:login" %}">Login</a>
                    </li>
                </ul>
    {% endif %}
            </div>
        </div>
    </nav>

User/templates/user/index.html
{% extends 'partials/base.html' %}
{% block title %}Profile Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        Profile Page
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <span class="h4"> Profile information</span> <a class="btn btn-dark btn-sm float-right"
                                    href="{% url "user:profile_update" %}">Edit</a>
                                <hr>
                                <table class="table bg-white table-borderless">
                                    <tbody>
                                        <tr>
                                            <th scope="row">Name</th>
                                            <td>{{ user.username }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Native Name</th>
                                            <td>{{ user.native_name }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">First Name</th>
                                            <td>{{ user.first_name }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Last Name</th>
                                            <td>{{ user.last_name }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Email</th>
                                            <td>{{ user.email }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Phone</th>
                                            <td>{{ user.phone_no }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Address</th>
                                            <td>{{ user.address }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-md-4">
                                <img class="img-thumbnail" src="{{ user.image.url }}" alt="profile-image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
        <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Logout Page</h4>
                <hr>
                <div class="alert alert-dark">
                    <h5>Please Login First To View Your Account Information</h5>
                </div>
                <a href="{% url 'user:login' %}">Login</a>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

User/templates/user/login.html
{% extends 'partials/base.html' %}
{% block title %}Login Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            {% for message in messages %}
                {% if message %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endif %}
            {% endfor %}
            <div class="border p-3 bg-white">
                <h4>Login Page</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-dark" type="submit" value="Login">
                    <a class = "mx-4" href="{% url "user:password_reset" %}">Forget Password</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

User/templates/user/logout.html
{% extends 'partials/base.html' %}
{% block title %}Logout Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Logout Page</h4>
                <hr>
                <div class="alert alert-dark">
                    <h5>You have been logged out</h5>
                </div>
                <a href="{% url 'user:login' %}">Login</a>
            </div>
        </div>
    </div>
{% endblock %}

User/templates/user/password_reset.html
{% extends 'partials/base.html' %}
{% block title %}Password Reset Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            {% for message in messages %}
                {% if message %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endif %}
            {% endfor %}
            <div class="border p-3 bg-white">
                <h4>Password Reset Page</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-dark" type="submit" value="Reset Password">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

User/templates/user/password_reset_complete.html
{% extends 'partials/base.html' %}
{% block title %}Password Reset Complete Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Password Reset Complete Page</h4>
                <hr>
                <div class="alert alert-success">
                    <h5>Now You can log in with your new password</h5>
                </div>
                <a href="{% url 'user:login' %}">Login</a>
            </div>
        </div>
    </div>
{% endblock %}

User/templates/user/password_reset_confirm.html
{% extends 'partials/base.html' %}
{% block title %}Password Reset Confirm Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            {% for message in messages %}
                {% if message %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endif %}
            {% endfor %}
            <div class="border p-3 bg-white">
                <h4>Password Reset Confirm Page</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-dark" type="submit" value="Confirm Password">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

User/templates/user/password_reset_done.html
{% extends 'partials/base.html' %}
{% block title %}Password Reset Done Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Password Reset Done Page</h4>
                <hr>
                <div class="alert alert-dark">
                    <h5>A mail has been sent to the email address you provided. It has instructions you need to follow to reset your password</h5>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

User/templates/user/register.html
{% extends "partials/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Register Page{% endblock %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Register Page</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-success" type="submit" value="Register">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

User/templates/user/update.html
{% extends 'partials/base.html' %}
{% block title %}Profile Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        Profile Page
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <span class="h4"> Profile information</span>
                                <hr>
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <input class="btn btn-dark" type="submit" value="Update">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}